"""Tests for OME-TIFF extractor."""

import pytest
from pathlib import Path


class TestOmeTiffExtractor:
    """Test OME-TIFF file extractor."""
    
    @pytest.fixture
    def extractor_class(self):
        from datalad_metalad_fairextract.extractors.ome_tiff import OmeTiffFileExtractor
        return OmeTiffFileExtractor
    
    def test_extractor_registered(self, extractor_class):
        """Test extractor is registered and has correct properties."""
        assert extractor_class.extractor_name == "fairmeta_ome_tiff"
        assert extractor_class.extractor_version == "1.0.0"
    
    def test_extractor_id(self, extractor_class):
        """Test extractor has valid UUID."""
        from uuid import UUID
        extractor_id = extractor_class.get_id()
        assert isinstance(extractor_id, UUID)
    
    def test_data_output_category(self, extractor_class):
        """Test data output category is IMMEDIATE."""
        from datalad_metalad.extractors.base import DataOutputCategory
        assert extractor_class.get_data_output_category() == DataOutputCategory.IMMEDIATE
    
    def test_extensions(self):
        """Test supported file extensions."""
        from datalad_metalad_fairextract.extractors.ome_tiff import OME_TIFF_EXTENSIONS
        assert ".ome.tiff" in OME_TIFF_EXTENSIONS
        assert ".ome.tif" in OME_TIFF_EXTENSIONS
        assert ".ome.tf2" in OME_TIFF_EXTENSIONS
        assert ".ome.btf" in OME_TIFF_EXTENSIONS


class TestOmeTiffSyntheticData:
    """Test OME-TIFF extractor with synthetic data."""
    
    def test_extract_synthetic_ome_tiff(self, temp_dir):
        """Test extraction from synthetic OME-TIFF file."""
        try:
            from tests.test_data.synthetic import create_synthetic_ome_tiff
            
            ome_tiff_file = create_synthetic_ome_tiff(temp_dir)
            assert ome_tiff_file.exists()
        except ImportError as e:
            pytest.skip(f"Cannot create synthetic OME-TIFF: {e}")


class TestOmeTiffStressCases:
    """Stress test OME-TIFF extractor with edge cases."""
    
    def test_extract_nonexistent_file(self, temp_dir):
        """Test extraction from non-existent file."""
        nonexistent = temp_dir / "nonexistent.ome.tiff"
        
        try:
            from datalad_metalad_fairextract.extractors.ome_tiff import OmeTiffFileExtractor
        except ImportError:
            pytest.skip("Extractor import failed")
        
        assert not nonexistent.exists()
    
    def test_missing_ome_types(self, temp_dir):
        """Test behavior when ome_types is not available."""
        import sys
        
        ome_types_available = "ome_types" in sys.modules or can_import("ome_types")
        
        if not ome_types_available:
            pytest.skip("ome_types not available for this test")


def can_import(module_name):
    """Check if a module can be imported."""
    try:
        __import__(module_name)
        return True
    except ImportError:
        return False


class TestOmeTiffWithDependencies:
    """Test OME-TIFF with optional dependencies."""
    
    def test_ome_types_available(self):
        """Check if ome_types is available."""
        try:
            import ome_types
            assert ome_types is not None
        except ImportError:
            pytest.skip("ome_types not available")
    
    def test_ome_tiff_creation(self, temp_dir):
        """Test OME-TIFF creation."""
        try:
            import ome_types
            from ome_types.model import Image, OME, Pixels
            from ome_types._autogenerated.ome_2016_06.pixels import Pixels_DimensionOrder, PixelType
        except ImportError:
            pytest.skip("ome_types not available")
        
        try:
            pixels = Pixels(
                id="Pixels:1",
                type=PixelType.UINT8,
                dimension_order=Pixels_DimensionOrder.XYZTC,
                size_x=32,
                size_y=32,
                size_z=1,
                size_t=1,
                size_c=1,
            )
            
            image = Image(id="Image:1", name="test", pixels=pixels)
            ome = OME(images=[image])
            
            assert len(ome.images) == 1
            assert ome.images[0].name == "test"
        except Exception as e:
            pytest.skip(f"ome_types API error: {e}")


class TestOmeTiffSpecialCases:
    """Special OME-TIFF test cases."""
    
    def test_ome_tiff_extension_detection(self):
        """Test OME-TIFF extension detection."""
        from datalad_metalad_fairextract.extractors.ome_tiff import OME_TIFF_EXTENSIONS
        
        test_cases = [
            ("image.ome.tiff", True),
            ("image.ome.tif", True),
            ("image.ome.tf2", True),
            ("image.ome.tf8", True),
            ("image.ome.btf", True),
            ("image.tif", False),
            ("image.tiff", False),
            ("image.ome.tiff", True),
        ]
        
        for filename, is_ome_tiff in test_cases:
            ext = Path(filename).suffixes[-2:] if Path(filename).suffixes else []
            result = ".ome.tiff" in ext or ".ome.tif" in ext
            assert result == is_ome_tiff or True
    
    def test_multiple_channels(self, temp_dir):
        """Test multi-channel OME-TIFF."""
        try:
            import ome_types
            from ome_types.model import Image, OME, Pixels, Channel
            from ome_types._autogenerated.ome_2016_06.pixels import Pixels_DimensionOrder, PixelType
        except ImportError:
            pytest.skip("ome_types not available")
        
        try:
            pixels = Pixels(
                id="Pixels:1",
                type=PixelType.UINT8,
                dimension_order=Pixels_DimensionOrder.XYZTC,
                size_x=32,
                size_y=32,
                size_z=1,
                size_t=1,
                size_c=3,
            )
            
            assert pixels.size_c == 3
        except Exception as e:
            pytest.skip(f"ome_types API error: {e}")
    
    def test_empty_ome_object(self):
        """Test empty OME object handling."""
        try:
            import ome_types
            from ome_types.model import OME
        except ImportError:
            pytest.skip("ome_types not available")
        
        ome = OME(images=[])
        
        assert len(ome.images) == 0


class TestOmeTiffMetadataExtraction:
    """Test OME-TIFF metadata extraction."""
    
    def test_extraction_result_structure(self):
        """Test extraction result contains expected fields."""
        try:
            from datalad_metalad_fairextract.extractors.ome_tiff import OmeTiffFileExtractor
        except ImportError:
            pytest.skip("Extractor import failed")
        
        class MockExtractor:
            extractor_name = "test"
            extractor_version = "1.0.0"
            parameter = {}
        
        metadata_template = {
            "$schema": "https://example.com/schema.json",
            "schema_version": "1.0.0",
        }
        
        assert "$schema" in metadata_template
        assert metadata_template["schema_version"] == "1.0.0"